# SPDX-License-Identifier: Apache-2.0
"""The CSF handle for Kimodo.

Kimodo generates a multi-prompt schedule by calling its `_generate` once per
segment from `_multiprompt`.  The handle wraps both bound methods on the model
instance (the kimodo sources stay untouched): while filtering is on, each
segment takes the gate decision for its own text and is generated by
`generate_filtered_segment`; a segment on which no rule fires runs the
original `_generate`, so it passes through exactly.

Later segments begin with transition frames blended from the previous one;
those frames are locked (never filtered).
"""
from __future__ import annotations

import contextlib
import copy
import types

import torch

from csf.filter.config import FilterConfig, SafeReferencePolicy
from csf.filter.handle import FilterHandle

from .filtered_generate import generate_filtered_segment, root_path_dims

_GENERATE_PARAMS = (
    "texts", "max_frames", "num_denoising_steps", "pad_mask", "first_heading_angle",
    "motion_mask", "observed_motion", "cfg_weight", "text_feat", "text_pad_mask",
    "guide_masks", "cfg_type",
)


class KimodoFilterHandle(FilterHandle):
    """Wraps a loaded Kimodo model's sampler with CSF."""

    def __init__(self, model, cfg: FilterConfig, policy: SafeReferencePolicy, encoder=None) -> None:
        cfg = copy.copy(cfg)
        cfg.pin_dims = root_path_dims(getattr(model, "motion_rep", None))
        cfg.root_dims = len(cfg.pin_dims)
        super().__init__(cfg, policy, encoder if encoder is not None else model.text_encoder)
        self._model = model
        self.enabled = False
        self._text_feats: dict[str, torch.Tensor] = {}
        self._segment = 0
        self._transition_frames = 5
        self._orig_generate = model._generate
        self._orig_multiprompt = model._multiprompt
        model._generate = types.MethodType(lambda _m, *a, **k: self._generate(*a, **k), model)
        model._multiprompt = types.MethodType(lambda _m, *a, **k: self._multiprompt(*a, **k), model)
        model._csf_handle = self

    def detach(self) -> None:
        """Restore the model's own `_generate` / `_multiprompt`."""
        self._model._generate = self._orig_generate
        self._model._multiprompt = self._orig_multiprompt
        if hasattr(self._model, "_csf_handle"):
            del self._model._csf_handle

    def _text_feat(self, text: str) -> torch.Tensor:
        """[1, 1, d] conditioning feature of `text`, cached."""
        if text not in self._text_feats:
            feat, _ = self._model.text_encoder([text])
            feat = feat[:, None] if feat.dim() == 2 else feat
            self._text_feats[text] = feat.to(self._model.device)
        return self._text_feats[text]

    @contextlib.contextmanager
    def filtering(self, prompts: list, durations: list, steps: int):  # noqa: ARG002
        """Filter the next generation (the decision is taken per segment)."""
        self.decisions = []
        self.enabled = True
        try:
            yield self
        finally:
            self.enabled = False

    def _multiprompt(self, *args, **kwargs):
        self._segment = 0
        self._transition_frames = kwargs.get("num_transition_frames", 5)
        return self._orig_multiprompt(*args, **kwargs)

    def _generate(self, *args, **kwargs):
        if not self.enabled:
            return self._orig_generate(*args, **kwargs)
        lock_head = 0 if self._segment == 0 else self._transition_frames
        self._segment += 1

        vals = {name: args[i] for i, name in enumerate(_GENERATE_PARAMS) if i < len(args)}
        vals.update({k: v for k, v in kwargs.items() if k in _GENERATE_PARAMS})
        texts = vals["texts"]
        seg_text = next((t for t in (texts or []) if t and t.strip()), "")
        decision = self.decide(seg_text)
        if decision.inactive:
            return self._orig_generate(*args, **kwargs)

        model = self._model
        dev = model.device
        text_feat, text_pad_mask = vals.get("text_feat"), vals.get("text_pad_mask")
        if text_feat is None:
            feat, lengths = model.text_encoder(texts)
            feat = feat.to(dev)
            empty = [len(t.strip()) == 0 for t in texts]
            feat[empty] = 0
            lengths = torch.tensor(lengths, device=dev)
            lengths[empty] = 0
            text_pad_mask = torch.arange(feat.shape[1], device=dev).expand(
                feat.shape[0], feat.shape[1]) < lengths[:, None]
            text_feat = feat

        pad_mask = vals.get("pad_mask")
        nf = int(pad_mask.shape[1]) if pad_mask is not None else int(vals["max_frames"])
        unsafe = torch.cat([self._text_feat(t) for t in self.cfg.unsafe_texts], 0)
        x, _info = generate_filtered_segment(
            model, self.cfg, unsafe,
            self._text_feat(decision.safe_reference), self._text_feat(self.policy.stand),
            text_feat, text_pad_mask, pad_mask,
            vals.get("motion_mask"), vals.get("observed_motion"), vals.get("first_heading_angle"),
            vals.get("cfg_weight", 2.0), vals.get("cfg_type"),
            nf, int(vals["num_denoising_steps"]),
            lock_head=lock_head, active_mask=decision.mask,
        )
        return x


def attach_kimodo_filter(model, cfg: FilterConfig, *, policy: SafeReferencePolicy,
                         encoder=None) -> KimodoFilterHandle:
    """`BackboneSpec.attach_filter` for Kimodo: one handle per model instance."""
    existing = getattr(model, "_csf_handle", None)
    if existing is not None:
        existing.detach()
    return KimodoFilterHandle(model, cfg, policy, encoder=encoder)
